version: '3.6'
services:
  iris:
    environment:
      - SAMPLE_TOKEN=${SAMPLE_TOKEN}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false --ISCAgent false --key /ISC/iris.key
    deploy:
      resources:
        limits:
          cpus: "4"
    ports:
      - 1972
      - 52795:52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev/
      - ./irislicense:/ISC
  activemq:
      hostname: activemq
      image: apache/activemq-classic:6.1.0
      ports:
        - "8161:8161" # Web console port
        - "61616:61616" # Default ActiveMQ port
      environment:
        - ACTIVEMQ_OPTS= -Djetty.host=0.0.0.0 -Djava.util.logging.config.file=logging.properties -Djava.security.auth.login.config=/opt/apache-activemq/conf/login.config
        - ACTIVEMQ_WEB_USER=admin
        - ACTIVEMQ_WEB_PASSWORD=admin
        - ACTIVEMQ_CONNECTION_USER=admin
        - ACTIVEMQ_CONNECTION_PASSWORD=admin
      volumes:
        - activemq-data:/opt/apache-activemq/data

volumes:
  activemq-data: